name: Shortumation
version: 0.1.6
slug: shortumation
image: asosnovsky/shortumation-{arch}
url: "https://github.com/asosnovsky/Shortumation"
description: "A homeassitant addon which provides better UI for automations & scripts."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8000
ingress_entry: "web/"
panel_icon: mdi:home-automation
hassio_role: manager
privileged:
  - SYS_RAWIO
host_network: false
auth_api: true
map:
  - config:rw
options: {}
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Main port for the API & Web.
