name: Shortumation
version: v0.3.1
slug: shortumation
image: asosnovsky/shortumation-{arch}
url: "https://github.com/asosnovsky/Shortumation"
description: "A homeassitant addon which provides better UI for automations & scripts."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8000
ingress_entry: "web/"
homeassistant_api: true
auth_api: true
panel_icon: mdi:home-automation
hassio_role: homeassistant
host_network: false
map:
  - config:rw
options: {}
ports:
  8000/tcp:
ports_description:
  8000/tcp: Main port for the API & Web.
