name: Shortumation
version: 0.0.6f
slug: shortumation
url: "https://github.com/asosnovsky/Shortumation"
description: "A homeassitant addon which provides better UI for automations & scripts."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8000
ingress_entry: "/web"
panel_icon: mdi:home-automation
hassio_role: manager
auth_api: true
privileged:
  - SYS_RAWIO
host_network: true
map:
  - config:rw
options: {}
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Main port for the API & Web.
