version: '3'
services:
  addon:
    image: "asosnovsky/shortumation-${ARCH:-amd64}:${BUILD_TAG:-edge}"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
      args:
        BUILD_ARCH: ${ARCH:-amd64}
        BUILD_VERSION: ${BUILD_TAG:-edge}
