version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host

  shortumation:
    # make sure to replace the ARCH with whatever system you are running!
    image: "asosnovsky/shortumation-${ARCH:-amd64}:${SHORTUMATION_VERSION:-latest}"
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./config:/config
    environment:
      - SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN}
      - HASSIO_WS=ws://host.docker.internal:8123/api/websocket
