name: "Manual Build"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version Number"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: "${{ github.event.inputs.version }} / ${{ matrix.arch }}"
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: home-assistant/builder@2022.03.1
        with:
          args: |
            --${{ matrix.arch }} \
            --version ${{ github.event.inputs.version }} \
            --target .
