name: "Manual Build"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version Number"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: "${{ github.event.inputs.version }} / ${{ matrix.arch }}"
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to Dockerhub
        uses: home-assistant/builder@2022.07.0
        with:
          args: |
            --${{ matrix.arch }} \
            --version ${{ github.event.inputs.version }} \
            --target .
