name: Deploy
env:
  MONITORED_FILES: "apparmor.txt build.yaml config.yaml Dockerfile data rootfs"
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.arch }}
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)-g$(echo ${{ github.sha }} | cut -c1-5 )

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ${{ steps.get_version.outputs.VERSION }} / ${{ matrix.arch }}
        uses: home-assistant/builder@2022.03.1
        with:
          args: |
            --version ${{ steps.get_version.outputs.VERSION }} \
            --${{ matrix.arch }} \
            --target . 