name: Build add-on
env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "apparmor.txt build.yaml config.yaml Dockerfile data rootfs"
on: 
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ github.ref }} / ${{ matrix.arch }} 
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ${{ matrix.arch }}
        run: |
          ARCH=${{ matrix.arch }} && \
          BUILD_TAG=${{ github.ref }} && \
          make build

      - name: Push ${{ matrix.arch }}
        run: |
          ARCH=${{ matrix.arch }} && \
          BUILD_TAG=${{ github.ref }} && \
          make push